"""
Patch models/16sectors_qc/economy.xlsx to add missing time index named ranges.
Keeps a backup as economy_pre_timeindex_backup.xlsx.
Same ranges will be generated by QC_IOT.py on next run.
"""
import zipfile, shutil, os, re
from lxml import etree

BACKUP = 'models/16sectors_qc/economy_pre_timeindex_backup.xlsx'
PATH   = 'models/16sectors_qc/economy.xlsx'
SRC    = BACKUP  # always read from clean backup
NS     = 'http://schemas.openxmlformats.org/spreadsheetml/2006/main'

print(f'Reading from backup: {SRC}')

WORLD_ID  = None
QUEBEC_ID = None

with zipfile.ZipFile(SRC) as z:
    tree = etree.fromstring(z.read('xl/workbook.xml'))
    sheets = tree.findall(f'.//{{{NS}}}sheet')
    for i, s in enumerate(sheets):
        name = s.get('name')
        print(f'  Sheet {i}: {name}')
        if name == 'World':
            WORLD_ID = str(i)
        elif name == 'Quebec':
            QUEBEC_ID = str(i)

print(f'World id={WORLD_ID}, Quebec id={QUEBEC_ID}')

# Named ranges to add.
# Layout: MultiIndex (2 levels) uses cols A-B; year data starts at col C (col 3).
# QC data covers 1995-2018 (24 years) -> cols C(3)..Z(26).
# All time indices must span the full 24-year data range so pysd lengths match.
# The names (time_index2009, time_index2014) are kept from the 14-sector convention
# but now cover all 24 years to match the actual data width.
#   time_index2009 / time_index2014 / time_index_2009 : C:Z (cols 3-26)
#   time_index_projection : header row of input_GDPpc_annual_growth (World row 199 / Quebec row 235)

NEW_RANGES = [
    ('time_index2009',        WORLD_ID,  'World!$C$1:$Z$1'),
    ('time_index2014',        WORLD_ID,  'World!$C$1:$Z$1'),
    ('time_index_projection', WORLD_ID,  'World!$C$199:$Z$199'),
    ('time_index_2009',       QUEBEC_ID, 'Quebec!$C$1:$Z$1'),
    ('time_index2009',        QUEBEC_ID, 'Quebec!$C$1:$Z$1'),
    ('time_index2014',        QUEBEC_ID, 'Quebec!$C$1:$Z$1'),
    ('time_index_projection', QUEBEC_ID, 'Quebec!$C$235:$Z$235'),
    # Typo alias: model references 'historic_goverment_expenditures' (missing 'n');
    # the 16-sector file uses the correct spelling. Add aliases for both sheets.
    ('historic_goverment_expenditures', WORLD_ID,  'World!$C$74:$Z$89'),
    ('historic_goverment_expenditures', QUEBEC_ID, 'Quebec!$C$74:$Z$89'),
]

tmp = PATH + '.tmp'
with zipfile.ZipFile(SRC, 'r') as zin, zipfile.ZipFile(tmp, 'w', zipfile.ZIP_DEFLATED) as zout:
    for item in zin.infolist():
        data = zin.read(item.filename)
        if item.filename == 'xl/workbook.xml':
            tree = etree.fromstring(data)
            names_el = tree.find(f'{{{NS}}}definedNames')
            if names_el is None:
                names_el = etree.SubElement(tree, f'{{{NS}}}definedNames')

            existing = {(dn.get('name'), dn.get('localSheetId'))
                        for dn in names_el.findall(f'{{{NS}}}definedName')}
            added = 0
            for name, sheet_id, ref in NEW_RANGES:
                if (name, sheet_id) not in existing:
                    el = etree.SubElement(names_el, f'{{{NS}}}definedName')
                    el.set('name', name)
                    el.set('localSheetId', sheet_id)
                    el.text = ref
                    print(f'  Added [{sheet_id}] {name} -> {ref}')
                    added += 1
                else:
                    print(f'  Already exists: [{sheet_id}] {name}')
            print(f'Added {added} named ranges.')
            data = etree.tostring(tree, xml_declaration=True, encoding='UTF-8', standalone=True)
        zout.writestr(item, data)

try:
    os.replace(tmp, PATH)
    print(f'Done. Written to {PATH}')
except PermissionError:
    out = PATH.replace('.xlsx', '_new.xlsx')
    os.replace(tmp, out)
    print(f'NOTE: {PATH} is open — close it, then rename economy_new.xlsx to economy.xlsx')
    print(f'Written to {out}')
